Update dialog.txt
GiAnMMV/EarthBound-Beginnings-ITA pull request #2
Opened 2023-04-18 10:34 UTC by HappyGitCake

righe 1-100

2023-04-18 14:27 UTC, GiAnMMV requested changes

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Pensavo che fossi# un bimbo sensibile.#|
Credo che "sensible" venga inteso come "ragionevole".

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Gli animali sembrano# impazziti, sono# fuori controllo.#_*I morti sono diventati# zombi ed hanno# attaccato la gente.#_*Che possiamo fare?#|
Cambierei "hanno attaccato" in "si sono messi ad attaccare" o "stanno attaccando".

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Sei magnifico!#|
Forse cambierei in "grande", visto che "magnifico" oggi viene usato perlopiù per indicare la bellezza fisica.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*C'è del pane raffermo# se vuoi MANGIARE,#_*ma, usando le sue# Briciole puoi segnare# il tuo sentiero.#_*Dici che sto# parlando troppo?# Allora?#|
Cambierei "MANGIARE" in "MANGIAre" per evidenziare solo l'opzione del menù (viene fatto anche in inglese con "USEd"), toglierei la virgola dopo il "ma" e cambiarei l'ultima riga in "E allora?".

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Cittadini, so# che vorreste soltanto# aiutare la città.#|
Qui va cambiato tutto al singolare, visto che il sindaco sta parlando solo a Ninten.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Dunque...# Un bimbo si è# perso nel cimitero.#_*Ed io...# candidando per le# prossime elezioni.#_*Devi aiutarmi!# Ti prego!#|
Qui a essersi persa nel cimitero è Pippi, quindi va cambiato il suo genere. Inoltre alla seconda frase penso manchi una parte, metterei "mi sto" prima di "candidando".

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Ma lei è la ragazza# perduta, Pippi?#_*Beh ma è# favoloso.#_*Sapevo che avresti# compiuto il tuo# dovere da cittadino.#_*Applausi,# applausi...#_*Ora piccola Pippi,# non dimenticare...#_*di dire a m
Qui cambierei "perduta" in "smarrita" o "dispersa", termini più adatti a indicare una persona. Inoltre cambierei "ti do" in "ecco", mi sembra più naturale.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Sì, ci andrai?# Fantastico, fantastico# fantastico!#_*Assicurati di prendere# una chiave dal mio# assistente, Abbott.#|
Qui il testo sfora dalla casella di testo. Inoltre metterei "chiave" con l'iniziale maiuscola, come in inglese.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Questa chiave aprirà il# cancello dello zoo.# Non perderla.#|
Credo che qui metterei "aprirà" al presente. Inoltre metterei "chiave" con l'iniziale maiuscola, come in inglese.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Restituiscimela viva,# e sicuramente# sarò un eroe...#_*Ehm, umh, voglio dire# sarai un eroe.#|
Qui cambierei "restituiscimela" in "riportamela", più adatto a una persona. Inoltre cambierei "umh" in "uhm".

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Perché se non è il# nostro eroe ¹£@,#_*Hai dello sterco di# tigre sui tuoi# vestiti?#_*Ha-ha, sto solo# scherzando. Adesso vai# ragazzo.#|
Qui il testo sfora. Inoltre cambierei "Perché" in "Guarda" e cambierei "Ha-ha" in Ah-ah".

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Se è gratis,# lo vuoi?# E prenditelo!#|
Forse cambierei l'ultima frase in "Prenditelo e basta!".

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Credo che qualcosa# stia controllando# gli animali.#|
Forse cambierei in `*Credo che qualcosa# abbia il controllo# degli animali.#|`

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Come posso aiutarti?# Hai qualcosa# da restituire?#|
Forse cambierei "restituire" in "darmi", visto che in pratica glielo stai vendendo.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Aspetta.. Una voce sta# parlando nella# mente di ¹£@.#|
Qui il testo sfora.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Grazie per# i vostri acquisti# con noi.#|
Qui cambierei in `*Grazie per aver# fatto acquisti# da noi.#|`

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Com'è comodo che# lo sportello Bancomat#_*sia qui accanto# al bancone, ma perché#_*dovrebbe interessarmi?# Non ho nemmeno una# carta da usare.#|
Qui mi si era presentato lo stesso problema traducendo un'altra linea: anch'io ho pensato di usare "Bancomat", ma ho poi scoperto che si tratta di marchio registrato, quindi nel dubbio metterei "sportello automatico".
Inoltre anche qui il testo sfora.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Ooh! Quel canarino# è il pulcino di# Laura cantante.#_*Le ridarai il# suo piccolo?#|
Qui "Laura cantante" mi suona un po' male, forse cambierei in "Laura canterina". Inoltre nell'ultima frase credo che il "will" sia da intendere come volontà e non come futuro, quindi cambierei in `*Vuoi ridarle il# suo piccolo?#|`.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Momento...#_*Ti sei appena perso# qualcosa di molto# importante.#|
Cambierei l'inizio in "Un momento".

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Dov'è Laura?...#|
Qui in base al contesto cambierei in `*Dove sarà Laura?...#|`.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Laura si ricordò# la sua canzone, ed iniziò# a cantarla nuovamente.#_*Hai appreso# la melodia?#|
Qui credo che metterei al passato prossimo per coerenza con gli altri casi.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Non darti tutte# queste arie.# Ha-ha-ha.#|
Qui cambierei "Ha-ha-ha" in "Ah-ah-ah".

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Sei coraggioso.# speriamo di# incontrarci ancora.#|
Qui forse cambierei "speriamo di incontrarci" in "spero di incontrarti"; inoltre ci va la maiuscola dopo la fine del periodo.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Sono così felice!  Per# ringraziarti prendi# questo regalo.#_*Un emblema che# ti proteggerà.# Ecco, tieni!#|
Qui il testo sfora. Inoltre cambierei "emblema" in "Medaglia" (con la maiuscola) per coerenza con il nome negli oggetti.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*YNon serviva che# tu rispondessi, tesoro.#|
Qui il testo sfora; inoltre hai lasciato la Y all'inizio.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
>  *EEE, EE EEK,# EEK EEK!#|
Qui metterei `*III, II IIH,# IIH IIH!#|`, per rendere meglio il verso della scimmia in italiano.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*¹£@ ha sentito questa# questa domanda# nella sua mente.#_*”Chi si è perso# la sua coda?”#|
Qui il testo sfora se il nome viene impostato più lungo di tre caratteri e c'è una ripetizione della parola "questa"; inoltre cambierei l'ultima frase in "Chi si è perso la coda" o "Chi ha perso la propria coda?".

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Cielo! che strani# vestiti che indossi!#_*Di certo i mostri# daranno la caccia# a questi indumenti!!#|
Qui non c'è la maiuscola dopo il punto di esclamazione. Inoltre credo che cambierei l'ultima frase in `*Di certo i mostri ti# daranno la caccia con# quegli indumenti!!#|`.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Ti disturba che# la tristezza#_*e la disgrazia ti# cerchino di continuo?#|
Qui cambierei in `*Temi che la# tristezza#_*e la disgrazia# posssano cercarti?#|`.

2023-04-18 14:27 UTC, GiAnMMV commented on dialog.txt
> +*Se non desideri# trovarti mai# nei guai...#_*RESTA A CASA!!#|
Cambierei in `*Se desideri di non# trovarti mai# nei guai...#_*RESTATENE A CASA!!#|`.

2023-04-18 15:00 UTC, HappyGitCake commented on dialog.txt
> +*Pensavo che fossi# un bimbo sensibile.#|
son d'accordo!

2023-04-18 15:06 UTC, HappyGitCake commented on dialog.txt
> +*Gli animali sembrano# impazziti, sono# fuori controllo.#_*I morti sono diventati# zombi ed hanno# attaccato la gente.#_*Che possiamo fare?#|
"stanno attaccando" va benissimo, modifico!

2023-04-18 15:07 UTC, HappyGitCake commented on dialog.txt
> +*Sei magnifico!#|
"grande" è poco, in originale è "super", quindi servirebbe qualcosa di più altisonante, tipo:
"Sei grandioso!"

Può andare?

2023-04-18 15:12 UTC, HappyGitCake commented on dialog.txt
> +*C'è del pane raffermo# se vuoi MANGIARE,#_*ma, usando le sue# Briciole puoi segnare# il tuo sentiero.#_*Dici che sto# parlando troppo?# Allora?#|
va bene

2023-04-18 15:12 UTC, HappyGitCake commented on dialog.txt
> +*Cittadini, so# che vorreste soltanto# aiutare la città.#|
ok!

2023-04-18 15:19 UTC, HappyGitCake commented on dialog.txt
> +*C'è del pane raffermo# se vuoi MANGIARE,#_*ma, usando le sue# Briciole puoi segnare# il tuo sentiero.#_*Dici che sto# parlando troppo?# Allora?#|
in inglese la frase è:
"Well, do I?"

che suona tipo:
"Ah sì? È così?"
o
"Ma davvero?"

che proponi?

2023-04-18 15:23 UTC, HappyGitCake commented on dialog.txt
>  *EEE, EE EEK,# EEK EEK!#|
Piuttosto una roba come:
*IIH, UH-UHH, UH-AHH!#|

come l'onomatopea italiana, o qualcosa di analogo

2023-04-18 15:26 UTC, HappyGitCake commented on dialog.txt
> +*¹£@ ha sentito questa# questa domanda# nella sua mente.#_*”Chi si è perso# la sua coda?”#|
vero, è un mio refuso, correggo;
`¹£@` è da considerarsi al massimo della sua lunghezza, cioè 7 caratteri - come da README;
"Chi si è perso la coda?" mi sembra più usato in un dialogo, "Chi ha perso la propria coda?" non so in quale contesto si utilizzi :) mi sa di molto formale

2023-04-18 15:29 UTC, HappyGitCake commented on dialog.txt
> +*Cielo! che strani# vestiti che indossi!#_*Di certo i mostri# daranno la caccia# a questi indumenti!!#|
perfetto, correggo!

2023-04-18 15:34 UTC, HappyGitCake commented on dialog.txt
> +*Ti disturba che# la tristezza#_*e la disgrazia ti# cerchino di continuo?#|
In realtà la frase non indica un dubbio, ma chiede proprio se sei turbato di essere inseguito da miseria e disgrazia:
`*Are you bothered that# unhappiness and#_*misfortune search# you out?#|`

propongo:
`*Sei turbato di# essere perseguitato#_*dalla disgrazia# e dallo sconforto?#|`

2023-04-18 15:37 UTC, HappyGitCake commented on dialog.txt
> +*Se non desideri# trovarti mai# nei guai...#_*RESTA A CASA!!#|
tolgo il `di` e aggiorno

2023-04-18 17:05 UTC, GiAnMMV commented on dialog.txt
> +*È vero?# I problemi# ti inseguono?#_*Mmh, che cosa# brutta.#|
Forse cambierei "che cosa brutta" in "che peccato".

2023-04-18 17:05 UTC, GiAnMMV commented on dialog.txt
> +*Sei magnifico!#|
Mi sembra il giusto compromesso, benissimo!

2023-04-18 17:05 UTC, GiAnMMV commented on dialog.txt
> +*Oh, cielo!# La nostra casa cade# a pezzi, fratellone!#|
Qui c'è un conflitto perché la tua versione non era aggiornata, quindi dovresti cambiare in `*Oh, cielo!# La nostra casa cade# a pezzi, fratellone!#|`.

2023-04-18 17:05 UTC, GiAnMMV commented on dialog.txt
> +*Oh, sei ferito.#|
Qui c'è un conflitto perché la tua versione non era aggiornata, quindi dovresti cambiare in `*Oh, qualcuno ti# ha ferito.#|`.

2023-04-18 17:05 UTC, GiAnMMV commented on dialog.txt
> +*Beh...# A quanto pare la# nostra casa è# infestata.#_*Non so di# preciso come...#_*Ma il tuo# bisnonno ha# studiato PSI.#_*Potresti trovare# qualcosa di utile# in cantina.#_*Ma ho lasciato la# Chiav
Qui c'è un conflitto perché la tua versione non era aggiornata, quindi dovresti cambiare in `*Beh...# A quanto pare la# nostra casa è# infestata.#_*Non so di# preciso come...#_*Ma il tuo# bisnonno ha# studiato PSI.#_*Potresti trovare# qualcosa di utile# in cantina.#_*Ma ho lasciato la# Chiave della Cantina# da qualche parte...#_*...non ricordo dove,# di preciso...#_*Comunque, figliolo,# sei la mia unica# speranza.#_*È ora che tu parta# per una piccola# avventura,#_*e che esplori le# potenzialità dei# tuoi poteri.#_*I poteri non vanno# presi con leggerezza.#_*Metticela tutta,# ¹÷[!!#_*Ma ricorda anche di# tornare a trovare# la tua famiglia.#_*Ciao.#_*Oh... telefonami e# mi assicurerò di#_*SALVAre i tuoi# progressi.#_*Chiamami per# qualunque cosa.#|`.

2023-04-18 17:05 UTC, GiAnMMV commented on dialog.txt
> +*C'è del pane raffermo# se vuoi MANGIARE,#_*ma, usando le sue# Briciole puoi segnare# il tuo sentiero.#_*Dici che sto# parlando troppo?# Allora?#|
Ah, forse l'avevo interpretata male. Credo che allora opterei per "È così".

2023-04-18 17:05 UTC, GiAnMMV commented on dialog.txt
>  *EEE, EE EEK,# EEK EEK!#|
Sì, ancora meglio!

2023-04-18 17:05 UTC, GiAnMMV commented on dialog.txt
> +*Ti disturba che# la tristezza#_*e la disgrazia ti# cerchino di continuo?#|
O forse anche "Sei preoccupato che...".

2023-04-18 17:05 UTC, GiAnMMV commented on dialog.txt
> +*Ti disturba che# la tristezza#_*e la disgrazia ti# cerchino di continuo?#|
Sì, probabilmente hai ragione, è un po' difficile senza contesto. L'ultima va bene, direi!

2023-04-19 07:54 UTC, GiAnMMV requested changes

2023-04-19 07:54 UTC, GiAnMMV commented on dialog.txt
> +*OK ragazzo, siamo# in un paese libero,# no?#|
Forse cambierei "no?" in "alla fine" o "d'altronde".

2023-04-19 07:54 UTC, GiAnMMV commented on dialog.txt
> +*È rimasto solo questo# pulcino di canarino.# Vuoi comprarlo?#|
Cambierei in "Pulcino di Canarino", visto che i nomi degli oggetti hanno le maiuscole.

2023-04-19 07:54 UTC, GiAnMMV commented on dialog.txt
> +*Quel pulcino di# canarino viene dal# Villaggio Canarino?#|
Cambierei in "Pulcino di Canarino", visto che i nomi degli oggetti hanno le maiuscole.

2023-04-19 11:16 UTC, HappyGitCake commented on dialog.txt
> +*È vero?# I problemi# ti inseguono?#_*Mmh, che cosa# brutta.#|
ok!

2023-04-19 11:19 UTC, HappyGitCake commented on dialog.txt
> +*Oh, cielo!# La nostra casa cade# a pezzi, fratellone!#|
fatto

2023-04-19 11:21 UTC, HappyGitCake commented on dialog.txt
> +*Beh...# A quanto pare la# nostra casa è# infestata.#_*Non so di# preciso come...#_*Ma il tuo# bisnonno ha# studiato PSI.#_*Potresti trovare# qualcosa di utile# in cantina.#_*Ma ho lasciato la# Chiav
aggiornato!

2023-04-19 11:24 UTC, HappyGitCake commented on dialog.txt
> +*OK ragazzo, siamo# in un paese libero,# no?#|
`d'altronde` è perfetto!

2023-04-26 11:04 UTC, HappyGitCake commented on dialog.txt
> +*Dunque...# Un bimbo si è# perso nel cimitero.#_*Ed io...# candidando per le# prossime elezioni.#_*Devi aiutarmi!# Ti prego!#|
giusto, m'era scivolato!
corretto

2023-04-26 11:08 UTC, HappyGitCake commented on dialog.txt
> +*Sì, ci andrai?# Fantastico, fantastico# fantastico!#_*Assicurati di prendere# una chiave dal mio# assistente, Abbott.#|
ok aggiunta maiuscola e cambiato in `# Fantastico, mitico# grandioso!#`

2023-04-26 11:08 UTC, HappyGitCake commented on dialog.txt
> +*Restituiscimela viva,# e sicuramente# sarò un eroe...#_*Ehm, umh, voglio dire# sarai un eroe.#|
fatto

2023-04-26 11:16 UTC, HappyGitCake commented on dialog.txt
> +*Perché se non è il# nostro eroe ¹£@,#_*Hai dello sterco di# tigre sui tuoi# vestiti?#_*Ha-ha, sto solo# scherzando. Adesso vai# ragazzo.#|
ok cambiato `Adesso` in `Ora` per rimanere nei 22 caratteri.

Il resto della frase non conoscendo il contento, mi sembra una battuta del tipo: "Perché se non sei il nostro eroe hai della cacca di tigre sul vestito?"

Solo che - come spesso accade in inglese - erroneamente non si mette il punto interrogativo in una domanda, quindi non sono certo se sia una frase interrogativa o affermativa.

Qual è il senso della frase?
Così la aggiustiamo

2023-04-26 11:17 UTC, HappyGitCake commented on dialog.txt
> +*Ma lei è la ragazza# perduta, Pippi?#_*Beh ma è# favoloso.#_*Sapevo che avresti# compiuto il tuo# dovere da cittadino.#_*Applausi,# applausi...#_*Ora piccola Pippi,# non dimenticare...#_*di dire a m
casomai cambiamo `Tieni` in `Ecco` ?

2023-04-26 11:18 UTC, HappyGitCake commented on dialog.txt
> +*Questa chiave aprirà il# cancello dello zoo.# Non perderla.#|
yeah

2023-04-26 11:20 UTC, HappyGitCake commented on dialog.txt
> +*Se è gratis,# lo vuoi?# E prenditelo!#|
okay

2023-04-26 11:21 UTC, HappyGitCake commented on dialog.txt
> +*Credo che qualcosa# stia controllando# gli animali.#|
va bene

2023-04-26 11:21 UTC, HappyGitCake commented on dialog.txt
> +*Come posso aiutarti?# Hai qualcosa# da restituire?#|
benone, correggo

2023-04-26 11:22 UTC, HappyGitCake commented on dialog.txt
> +*Aspetta.. Una voce sta# parlando nella# mente di ¹£@.#|
dove?

2023-04-26 11:23 UTC, HappyGitCake commented on dialog.txt
> +*Grazie per# i vostri acquisti# con noi.#|
ok

2023-04-26 11:28 UTC, HappyGitCake commented on dialog.txt
> +*Com'è comodo che# lo sportello Bancomat#_*sia qui accanto# al bancone, ma perché#_*dovrebbe interessarmi?# Non ho nemmeno una# carta da usare.#|
va bene, risolto.

2023-04-26 11:29 UTC, HappyGitCake commented on dialog.txt
> +*Ooh! Quel canarino# è il pulcino di# Laura cantante.#_*Le ridarai il# suo piccolo?#|
concordo!
e provvedo

2023-04-26 11:30 UTC, HappyGitCake commented on dialog.txt
> +*Momento...#_*Ti sei appena perso# qualcosa di molto# importante.#|
fatto

2023-04-26 11:42 UTC, HappyGitCake commented on dialog.txt
> +*Laura si ricordò# la sua canzone, ed iniziò# a cantarla nuovamente.#_*Hai appreso# la melodia?#|
ok corretto in:
`*Laura si è ricordata# la sua canzone, ed ha# iniziato a cantarla#_* di nuovo. Hai appreso# la melodia?#|`

2023-04-26 11:50 UTC, HappyGitCake commented on dialog.txt
> +*Sono così felice!  Per# ringraziarti prendi# questo regalo.#_*Un emblema che# ti proteggerà.# Ecco, tieni!#|
cambiato in `Medaglia`, ma non vedo lo sforo, la lunghezza delle frasi è:
22, 20, 15, 16, 15, 13
contando solo le lettere, gli spazi e la punteggiatura.
Vanno calcolati anche i caratteri iniziali? Tipo asterisco, underscore..

2023-04-26 12:42 UTC, GiAnMMV commented on dialog.txt
> +*Laura si ricordò# la sua canzone, ed iniziò# a cantarla nuovamente.#_*Hai appreso# la melodia?#|
Forse graficamente sarebbe meglio `*Laura si è ricordata# la sua canzone#_*e ha ricominciato di# nuovo a cantarla.#_*Hai appreso la# melodia?#|`

2023-04-26 12:55 UTC, GiAnMMV commented on dialog.txt
> +*Sono così felice!  Per# ringraziarti prendi# questo regalo.#_*Un emblema che# ti proteggerà.# Ecco, tieni!#|
Sì, c'è un doppio spazio tra "felice!" e "Per" e risulta lungo 23.
Comunque sì, gli asterischi sono inclusi nel conteggio perché visibili, mentre i trattini bassi no, visto che sono pause e non caratteri visibili.

2023-04-26 12:55 UTC, GiAnMMV commented on dialog.txt
> +*Aspetta.. Una voce sta# parlando nella# mente di ¹£@.#|
Nella prima riga, lunga 23.

2023-04-26 13:15 UTC, GiAnMMV commented on dialog.txt
> +*Perché se non è il# nostro eroe ¹£@,#_*Hai dello sterco di# tigre sui tuoi# vestiti?#_*Ha-ha, sto solo# scherzando. Adesso vai# ragazzo.#|
Dunque, la frase viene detta se interagisci col Sindaco dopo che Ninten ha risolto la faccenda dello Zoo. Purtroppo non so di preciso come venga intesa, non essendo rilevante per la trama, opzionale e isolata; inoltre ci sono altre cose strane che la rendono ancora più dubbia, per esempio la maiuscola dopo la virgola.
Rileggendola e confrontandola con la traduzione del testo giapponese (automatica però, quindi non so fin quanto affidarmici) penso che sia da intendere come "Non sei il nostro eroe Ninten, [visto che] hai dello sterco di tigre sui vestiti" e la battuta starebbe nel fatto che fa finta di non riconoscerlo perché è sporco.
Non saprei, secondo te potrebbe aver senso?

2023-04-26 13:26 UTC, HappyGitCake commented on dialog.txt
> +*Sono così felice!  Per# ringraziarti prendi# questo regalo.#_*Un emblema che# ti proteggerà.# Ecco, tieni!#|
capisco!
Ok correggo

2023-04-26 14:00 UTC, HappyGitCake commented on dialog.txt
> +*Perché se non è il# nostro eroe ¹£@,#_*Hai dello sterco di# tigre sui tuoi# vestiti?#_*Ha-ha, sto solo# scherzando. Adesso vai# ragazzo.#|
penso il senso sia sempre di fare una battuta infelice, ma al contrario, tipo:
"si vede che sei tu perché sei sporco di cacca di tigre ahah" (che ridere) "adesso fuori dalle scatole"
messa come "chi altri se non il nostro eroe, potrebbe essere sporco di cacca?"

propongo:
`*Chi altri, se non il# nostro eroe ¹£@,#_*avrebbe sterco di# tigre sui suoi# vestiti?#_*Ha-ha, sto solo# scherzando. Ora vai# ragazzo.#|`

2023-04-26 14:01 UTC, HappyGitCake commented on dialog.txt
> +*Aspetta.. Una voce sta# parlando nella# mente di ¹£@.#|
ok corretto!

2023-04-26 14:10 UTC, GiAnMMV commented on dialog.txt
> +*Perché se non è il# nostro eroe ¹£@,#_*Hai dello sterco di# tigre sui tuoi# vestiti?#_*Ha-ha, sto solo# scherzando. Adesso vai# ragazzo.#|
Direi che va bene! Consiglierei comunque di cambiare "Ha-ha" in "Ah-ah", credo sia più corretto in italiano.

2023-04-26 14:17 UTC, HappyGitCake commented on dialog.txt
> +*Laura si ricordò# la sua canzone, ed iniziò# a cantarla nuovamente.#_*Hai appreso# la melodia?#|
In un video _long run_ su youtube ho visto un'altra traduzione ENG che dice:
`Overjoyed with her reunion, Laura began singing. Ninten remembered the melody.`
che ha tutto un altro senso, cioè sembra essersi 'sbloccata' perché ha rivisto il suo pulcino, e quindi prende a cantare.
Hai modo di risalire all'originale giapponese? Così cerchiamo di tirar fuori qualcosa di più consono.
Proporrei qualcosa come:
`*Felicissima di aver# riavuto il suo#_ Canarino, Laura ha# iniziato a cantare.#_*¹£@ ha imparato# la melodia.#|`

2023-04-26 14:49 UTC, GiAnMMV commented on dialog.txt
> +*Laura si ricordò# la sua canzone, ed iniziò# a cantarla nuovamente.#_*Hai appreso# la melodia?#|
Oh, no, scusa per l'incomprensione! Quella che dici tu non viene da un'altra traduzione, ma da un altro dialogo. Questa frase non viene detta da Laura ma da un altro PNG nel Villaggio Canarino.

2023-04-27 06:17 UTC, GiAnMMV commented on dialog.txt
> +*Perché se non è il# nostro eroe ¹£@,#_*Hai dello sterco di# tigre sui tuoi# vestiti?#_*Ha-ha, sto solo# scherzando. Adesso vai# ragazzo.#|
Inoltre cambierei "vai" in "fila via", mi suona più sprezzante e nep personaggio.

2023-05-01 12:46 UTC, HappyGitCake commented on dialog.txt
> +*Laura si ricordò# la sua canzone, ed iniziò# a cantarla nuovamente.#_*Hai appreso# la melodia?#|
non so se è lo stesso che ho visto, Laura sembra essere in un'altra situazione:
ecco il video che ho visto
[Minuto 26:50](https://youtu.be/xTonuqUL_MU?t=1610)

2023-05-01 12:47 UTC, HappyGitCake commented on dialog.txt
> +*Perché se non è il# nostro eroe ¹£@,#_*Hai dello sterco di# tigre sui tuoi# vestiti?#_*Ha-ha, sto solo# scherzando. Adesso vai# ragazzo.#|
perfetto!
modifico

2023-05-01 13:19 UTC, GiAnMMV commented on dialog.txt
> +*Laura si ricordò# la sua canzone, ed iniziò# a cantarla nuovamente.#_*Hai appreso# la melodia?#|
Forse questo video può darti un'idea migliore del contesto generale: [https://youtu.be/6r6EWhzFDH0](https://youtu.be/6r6EWhzFDH0).

2023-05-01 13:34 UTC, HappyGitCake commented on dialog.txt
> +*Laura si ricordò# la sua canzone, ed iniziò# a cantarla nuovamente.#_*Hai appreso# la melodia?#|
ma quindi e` il signore semi calvo che lo dice!
Ho capito ora, corretto!

2023-05-01 13:48 UTC, merged